yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),

    path('group/<slug:slug>/', views.group_posts, name='group_list'),

    path('profile/<str:username>/', views.profile, name='profile'),

    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),

    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),

    path('create/', views.post_create, name='post_create'),

    path('posts/<int:post_id>/comment/',
         views.add_comment, name='add_comment'),

    path('follow/', views.follow_index, name='follow_index'),

    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    )]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

handler404 = 'core.views.page_not_found'
handler403 = 'core.views.csrf_failure'
urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls'))
]
if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model

from yatube.settings import FIRST_POST_SYMBOLS

User = get_user_model()


class Group(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(max_length=100, unique=True)
    description = models.TextField(null=True, blank=True)

    def __str__(self):
        return self.title


class Post(models.Model):
    text = models.TextField(
        'Текст поста',
        help_text='Введите текст поста'
    )
    pub_date = models.DateTimeField(
        'Дата публикации',
        auto_now_add=True
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='Автор'
    )
    group = models.ForeignKey(
        Group,
        on_delete=models.SET_NULL,
        related_name='posts',
        blank=True,
        null=True,
        verbose_name='Группа',
        help_text='Выберите группу'
    )
    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True
    )

    class Meta:
        ordering = ('-pub_date',)
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'

    def __str__(self):
        return self.text[:FIRST_POST_SYMBOLS]


class Comment(models.Model):
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='comments')
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments')
    text = text = models.TextField(
        'Текст поста',
        help_text='Введите текст комментария'
    )
    created = models.DateTimeField(
        'Дата публикации',
        auto_now_add=True
    )


class Follow(models.Model):
    class Meta:
        db_table = 'posts_follow'
        constraints = [
            models.UniqueConstraint(fields=['user', 'author'],
                                    name='unique_follow')]
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='follower')
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='following')

yatube/posts/forms.py
from django import forms

from .models import Post, Comment


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'group', 'image')
        labels = {'text': 'Введите текст', 'group': 'Выберите группу'}
        help_texts = {'text': 'Текст вашего поста', 'group': 'Список групп'}
        widgets = {
            'group': forms.Select()
        }


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)
        labels = {'text': 'Введите текст', }
        help_texts = {'text': 'Текст вашего поста', }

yatube/posts/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect
from django.views.decorators.cache import cache_page

from .models import Post, Group, User, Comment, Follow
from .forms import PostForm, CommentForm
from .utils import paginator_arrange


@cache_page(20)
def index(request):
    post_list = Post.objects.all()
    page_obj = paginator_arrange(request, post_list)
    context = {
        'page_obj': page_obj,
    }
    return render(request, 'posts/index.html', context)


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    post_list = Post.objects.filter(group=group)
    page_obj = paginator_arrange(request, post_list)
    context = {
        'group': group,
        'page_obj': page_obj,
    }
    return render(request, 'posts/group_list.html', context)


@cache_page(20)
def profile(request, username):
    author = get_object_or_404(User, username=username)
    post_list = author.posts.all()
    page_obj = paginator_arrange(request, post_list)
    if request.user.is_authenticated:
        following = Follow.objects.filter(user=request.user,
                                          author=author).exists()
    else:
        following = False
    context = {'author': author,
               'page_obj': page_obj,
               'following': following,
               }
    return render(request, 'posts/profile.html', context)


@cache_page(20)
def post_detail(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    form = CommentForm(request.POST or None)
    comments = Comment.objects.filter(post=post).order_by('created')
    context = {'post': post,
               'form': form,
               'comments': comments
               }
    return render(request, 'posts/posts.html', context)


@cache_page(20)
@login_required
def post_create(request):
    form = PostForm(request.POST or None,
                    files=request.FILES or None)
    if form.is_valid():
        post = form.save(commit=False)
        post.author_id = request.user.id
        post.save()
        return redirect('posts:profile', request.user.username)
    template = 'posts/create_post.html'
    context = {
        'form': form,
        'is_edit': False,
    }
    return render(request, template, context)


@cache_page(20)
@login_required
def post_edit(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    if request.user != post.author:
        return redirect('posts:post_detail', post_id)
    form = PostForm(request.POST or None,
                    files=request.FILES or None, instance=post)
    if request.method == 'POST':
        if form.is_valid():
            form.save()
            return redirect('posts:post_detail', post_id)
        return render(request, 'posts/create_post.html', {'form': form})
    context = {
        'form': form,
        'post': post,
        'is_edit': True
    }
    return render(request, 'posts/create_post.html', context)


@cache_page(20)
@login_required
def add_comment(request, post_id):
    form = CommentForm(request.POST or None)
    post = get_object_or_404(Post, pk=post_id)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def follow_index(request):
    post_list = Post.objects.filter(
        author__following__user=request.user,)
    page_obj = paginator_arrange(request, post_list)
    context = {'page_obj': page_obj}
    return render(request, 'posts/follow.html', context)


@login_required
def profile_follow(request, username):
    author = get_object_or_404(User, username=username)
    if author != request.user:
        Follow.objects.get_or_create(user=request.user, author=author)
    context = {
        'username': username
    }
    return render(request, 'posts/profile_follow.html', context)


@login_required
def profile_unfollow(request, username):
    author = get_object_or_404(User, username=username)
    get_object_or_404(Follow, user=request.user, author=author).delete()
    context = {
        'username': username
    }
    return render(request, 'posts/profile_unfollow.html', context)

yatube/templates/posts/create_post.html
{% extends "base.html" %}
{% load thumbnail %}
{% load cache%}
{% block header %}
    {% if is_edit %}
        Редактирование поста
    {% else %}
        Создание нового поста
    {% endif %}
{% endblock %}
{% block content %}
  {% cache 20 sidebar %}
  <div class="container py-5">
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">       
            {% if is_edit %}
              Редактироват пост
            {% else %}
              Создать пост
            {% endif %}             
          </div>
          <div class="card-body">
            {% if is_edit %}
        <form action="{% url 'posts:post_edit' post.id %}" method="post" enctype="multipart/form-data">
            {% else %}        
            <form method="post" action="{% url 'posts:profile' request.user.username %}">
            {% endif %}
          <form method="post" enctype="multipart/form-data">
            {% csrf_token %}            
            {% for field in form %}
             <div class="form-group row" aria-required={% if field.field.required %}"true"{% else %}"false"{% endif %}>
             <label for="{{ field.id_for_label }}" class="col-md-3 col-form-label text-md-right">
                 {{ field.label }}{% if field.field.required %}<span class="required">*</span>{% endif %}</label>
             <div class="col-md-3">
                 {{ field }}
                 {% if field.help_text %}
                     <small id="{{ field.id_for_label }}-help"
                      class="form-text text-muted">{{ field.help_text|safe }}
                    </small>
                 {% endif %}
             </div>
             </div>
            {% endfor %}
              <div class="d-flex justify-content-end">
                <button type="submit" class="save btn btn-default">
                  {% if is_edit %}
                      Сохранить
                  {% else %}
                      Создать пост
                  {% endif %}
                </button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
  {% endcache %}
{% endblock %}

yatube/templates/posts/follow.html
{% extends 'base.html' %} 
{% load thumbnail %}
{% load cache %}
{% block title %}
    Ваши подписки
{% endblock %}
{% block content %}
    {% cache 20 sidebar %}
    {% include 'posts/includes/switcher.html' with follow=True%}
      <div class="container py-5">        
        {% for post in page_obj %}
            <ul>
                <li>
                Автор: {{ post.author }}
                <a href="{% url 'posts:profile' username=author.username %}">все посты пользователя</a>
                </li>
                <li>
                Дата публикации: {{ post.pub_date|date:"d E Y" }}
                </li>
            </ul>
            <p>{{ post.text }}</p>
            {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
                <img class="card-img my-2" src="{{ im.url }}">
            {% endthumbnail %}
            <a href="{% url 'posts:post_detail' post_id=post.id %}">подробная информация </a> 
            {% if post.group %}      
                <a href="{% url 'posts:group_list' slug=post.group.slug %}">все записи группы</a>   
            {% endif %}
        {% endfor %}      
        {% include 'posts/includes/paginator.html' %}
      </div>
    {% endcache %} 
{% endblock %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %} 
{% load thumbnail %}
{% block title %}
   Записи сообщества {{group.title}}
{% endblock %}

{% block content %} 
  <h1>{{ group.title }}</h1>
  <p>{{ group.description }}</p>
    {% for post in page_obj %}
    <ul>
      <li>
        Автор: {{ post.author.get_full_name }}
      </li>
      <li>
        Дата публикации: {{ post.pub_date|date:"d E Y" }}
      </li>
    </ul>
    {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
      <img class="card-img my-2" src="{{ im.url }}">
    {% endthumbnail %}
    <p>{{ post.text }}</p>    
    {% endfor %} 
    {% include 'posts/includes/paginator.html' %}
{% endblock %} 

yatube/templates/posts/index.html
{% extends 'base.html' %} 
{% load thumbnail %}
{% load cache%}
{% block title %}
  Последние обновления на сайте 
{% endblock %}
{% block content %}
  {% cache 20 sidebar %}
  {% include 'posts/includes/switcher.html' with index=True %}
  {% for post in page_obj %}
      <ul>
        <li>
          Автор: {{ post.author.get_full_name }}
        </li>
        <li>
          Дата публикации: {{ post.pub_date|date:"d E Y" }}
        </li>
      </ul>
      {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
        <img class="card-img my-2" src="{{ im.url }}">
      {% endthumbnail %}
      <p>{{ post.text }}</p>    
      {% if post.group %}   
        <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
      {% endif %} 
      {% if not forloop.last %}<hr>{% endif %}
  {% endfor %} 
  {% include 'posts/includes/paginator.html' %}
  {% endcache %} 
{% endblock %} 

yatube/templates/posts/posts.html
{% extends 'base.html' %} 
{% load thumbnail %}
{% load cache%}
{% block title %}
  Пост {{ post.text|truncatechars:30 }}
{% endblock %}

{% block content %}
  {% cache 20 sidebar %}
    <main>
      <div class="row">
        <aside class="col-12 col-md-3">
          <ul class="list-group list-group-flush">
            <li class="list-group-item">
              Дата публикации: {{ post.pub_date|date:'d E Y' }}
            </li>
            {% if post.group %}  
                <li class="list-group-item">
                Группа: {{ post.group.title }}
                <a href="{% url 'posts:group_list' post.group.slug %}">
                    все записи группы
                </a>
                </li>
            <li class="list-group-item">
            {% endif %}
              Автор: {{ post.author }}
            </li>
            <li class="list-group-item d-flex justify-content-between align-items-center">
              Всего постов автора:  <span >{{ post.author.posts.count }}</span>
            </li>
            <li class="list-group-item">
              <a href="{% url 'posts:profile' post.author.username %}">
                все посты пользователя
              </a>
            </li>
            {% if post.author == request.user %}
              <a href="{% url 'posts:post_edit' post_id=post.id %}">
                Редактировать пост
              <a>
            {% endif %}
          </ul>
        </aside>
        <article class="col-12 col-md-9">
          {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
            <img class="card-img my-2" src="{{ im.url }}">
          {% endthumbnail %}
          <p>
           {{ post.text|linebreaksbr }}
          </p>
        </article>
      </div>
      {% load user_filters %}

      {% if user.is_authenticated %}
        <div class="card my-4">
          <h5 class="card-header">Добавить комментарий:</h5>
          <div class="card-body">
            <form method="post" action="{% url 'posts:add_comment' post.id %}">
              {% csrf_token %}      
              <div class="form-group mb-2">
                {{ form.text|addclass:"form-control" }}
              </div>
              <button type="submit" class="btn btn-primary">Отправить</button>
            </form>
          </div>
        </div>
      {% endif %}

      {% for comment in comments %}
        <div class="media mb-4">
          <div class="media-body">
            <h5 class="mt-0">
              <a href="{% url 'posts:profile' comment.author.username %}">
                {{ comment.author.username }}
              </a>
            </h5>
            <p>
              {{ comment.text }}
            </p>
          </div>
        </div>
      {% endfor %} 
    </main>
  {% endcache %} 
{% endblock %}

yatube/templates/posts/profile.html
{% extends 'base.html' %} 
{% load thumbnail %}
{% load cache %}
{% block title %}
    Профайл пользователя {{ author }}
{% endblock %}
{% block content %}
    {% cache 20 sidebar %}
      <div class="container py-5">        
        <h1>Все посты пользователя {{ author }} </h1>
        <h3>Всего постов: {{ author.posts.count }} </h3> 
        {% if following %}
            <a
            class="btn btn-lg btn-light"
            href="{% url 'posts:profile_unfollow' author.username %}" role="button"
            >
            Отписаться
            </a>
        {% else %}
            <a
                class="btn btn-lg btn-primary"
                href="{% url 'posts:profile_follow' author.username %}" role="button"
            >
                Подписаться
            </a>
        {% endif %}  
        {% for post in page_obj %}
            <ul>
                <li>
                Автор: {{ author }}
                <a href="{% url 'posts:profile' username=author.username %}">все посты пользователя</a>
                </li>
                <li>
                Дата публикации: {{ post.pub_date|date:"d E Y" }}
                </li>
            </ul>
            <p>{{ post.text }}</p>
            {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
                <img class="card-img my-2" src="{{ im.url }}">
            {% endthumbnail %}
            <a href="{% url 'posts:post_detail' post_id=post.id %}">подробная информация </a> 
            {% if post.group %}      
                <a href="{% url 'posts:group_list' slug=post.group.slug %}">все записи группы</a>   
            {% endif %}
        {% endfor %}      
        {% include 'posts/includes/paginator.html' %}
      </div>
    {% endcache %} 
{% endblock %}

yatube/templates/posts/profile_follow.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Подписка на {{ username }}{% endblock %}
{% block content %}
    Поздравляем с успешной подпиской на пользователя {{ username }} :З
{%endblock%}

yatube/templates/posts/profile_unfollow.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Подписка на {{ username }}{% endblock %}
{% block content %}
    Поздравляем с успешной отпиской от пользователя {{ username }} :З
{%endblock%}